### ISSUE TITLE
Locker number search behaves in mysterious ways

### ISSUE THREAD

**Issue by zvdv** [zvdv/ECSS-Lockers#3]
When searching for lower-numbered lockers, you must input the leading zeroes for them to come up in the search (e.g. 1 comes up with 100, 101, etc. while 00 comes up with 001, 002, etc.). But as soon as you type a number other than 0, it goes back to only displaying 3-digit results starting with that number.
![image](https://github.com/user-attachments/assets/cdc231dd-a914-4ea8-a808-8aa103813544)
![image](https://github.com/user-attachments/assets/ae9fea51-83b1-4acd-a8d3-76ae2d4e7850)

**Comment by parsa222** [comment]
it might have something to do with the numbers being stored as strings or how the input is being parsed. I'll work on it.
